### PR TITLE
General maintenance of reqwire

### PR DESCRIPTION
**Pull request by ticosax**
- piptools1.9+
- update packages
- test against python3.6
- linter cleanups

This will require a major version bump change, as it breaks backward compatibility.

### CODE REVIEW

**Comment by ticosax** [comment]
I was wrong stating this require a major version bump, because it doesn't affect user experience right ?

**Comment by ticosax** [comment]
@darvid just realized you already made the release. So no worry, nothing important here.
Thank you BTW.

**Comment by darvid** [comment]
@ticosax Sorry didn't get a chance to comment, but thank _you_ for the PR! Just wanted to get it merged and released asap last night. For now I released it as 0.2.x instead of finishing out 0.1.x, I don't think we are quite ready for a 1.0, or if that will ever happen.

**Comment by ticosax** [comment]
I agree :) we need more users before getting 1.0 out of the door.
That said I'm not a believer of the 1.0 milestone. A project is always under maintenance. I tend to follow semver without paying attention to the "1.0" thing, which is sometimes perceived as a ideal state which prevent projects to move forward by fear to miss something.

**Comment by ticosax** [comment]
speaking about bringing more users: https://github.com/jazzband/pip-tools/pull/494
let's see.

**Pull request merged**
